// Generated by eve-rails. Do not edit generated regions.
// agent: billing
// template: tool.ts.j2

import { defineTool } from "eve/tools";
import { z } from "zod";

export default defineTool({
  description: "Generated prepare_refund money tool contract.",
  inputSchema: z.object({}),
  async execute() {
    return {
      status: "not_implemented",
      tool: "prepare_refund",
    };
  },
});
