// Generated by eve-rails. Do not edit generated regions.
// agent: support
// template: subagent-agent

import { defineAgent } from "eve";

export default defineAgent({
  description: "Generated policy_checker subagent skeleton.",
  model: "xai/grok-4.5",
});
