// Generated by eve-rails. Do not edit generated regions.
// agent: support
// template: tool.ts.j2

import { defineTool } from "eve/tools";
import { z } from "zod";

export default defineTool({
  description: "Generated create_ticket write tool contract.",
  inputSchema: z.object({}),
  async execute() {
    return {
      status: "not_implemented",
      tool: "create_ticket",
    };
  },
});
