// Generated by eve-rails. Do not edit generated regions.
// agent: support
// template: tool.ts.j2

import { defineTool } from "eve/tools";
import { z } from "zod";

export default defineTool({
  description: "Generated read tool contract.",
  inputSchema: z.object({}),
  async execute() {
    return {
      status: "not_implemented",
      tool: "lookup_policy",
    };
  },
});
