// Generated by eve-rails. Do not edit generated regions.
// agent: billing
// template: schedule.ts.j2

import { defineSchedule } from "eve/schedules";

export default defineSchedule({
  cron: "0 9 * * 1-5",
  markdown: "Run scheduled task weekday_triage and report only material findings.",
});
